DEFAULT leap
TIMEOUT 30

LABEL leap
    MENU LABEL LEAP Linux
    LINUX /Image
    FDT /bcm2711-rpi-4-b.dtb
    APPEND root=/dev/mmcblk0p2 rootwait usb-storage.quirks=152d:0579:u 8250.nr_uarts=1 console=tty1 console=ttyS0,115200
