DEFAULT leap-a
TIMEOUT 30

LABEL leap-a
    MENU LABEL LEAP Linux
    LINUX /Image
    FDT /bcm2711-rpi-4-b.dtb
    APPEND root=PARTUUID=546798d9-ce3b-45e1-b9b9-452728cbf974 rootwait usb-storage.quirks=152d:0579:u 8250.nr_uarts=1 console=tty1 console=ttyS0,115200

LABEL leap-b
    MENU LABEL LEAP Linux
    LINUX /Image
    FDT /bcm2711-rpi-4-b.dtb
    APPEND root=PARTUUID=2656ef9e-8e89-409e-a79d-7f808dbc9c4e rootwait usb-storage.quirks=152d:0579:u 8250.nr_uarts=1 console=tty1 console=ttyS0,115200
