DEFAULT leap
TIMEOUT 30

LABEL leap
    MENU LABEL LEAP Linux
    LINUX /boot/Image
    FDT /boot/bcm2711-rpi-4-b.dtb
    APPEND root=PARTUUID=${rootpartuuid} rootwait usb-storage.quirks=152d:0579:u 8250.nr_uarts=1 console=tty1 console=ttyS0,115200
